//! protocol-plugin world: WIT bindings (async) + host implementations (transport/metrics/log implemented directly on the store data).
//!
//! Networking and timing belong to the host: plugins read/write the network via host-transport handles (TCP/TLS/timeout guaranteed by the host).

use std::collections::HashMap;
use std::net::TcpStream;
use std::sync::Arc;

use wasmtime::component::{bindgen, Component, Linker};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{ResourceTable, WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

bindgen!({
    path: "../orbit-plugin-api/wit/protocol",
    world: "protocol-plugin",
});

/// host-transport default read/write timeout (satisfies the design's "host-unified timeout")
const DEFAULT_SOCKET_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(30);

/// Host state for a protocol plugin instance: connection table (synchronous blocking + timeout) + WASI ctx
pub struct ProtocolHostState {
    pub conns: HashMap<u32, TcpStream>,
    pub next_conn: u32,
    /// WASI preview2 context (wasip2 components importing wasi:io/clocks via std need the host to provide it)
    pub wasi: WasiCtx,
    /// WASI resource table
    pub table: ResourceTable,
}

impl wasmtime::component::HasData for ProtocolHostState {
    type Data<'a> = &'a mut ProtocolHostState;
}

impl WasiView for ProtocolHostState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.wasi,
            table: &mut self.table,
        }
    }
}

impl Default for ProtocolHostState {
    fn default() -> Self {
        Self::new()
    }
}

impl ProtocolHostState {
    pub fn new() -> Self {
        Self {
            conns: HashMap::new(),
            next_conn: 0,
            wasi: WasiCtxBuilder::new().build(),
            table: ResourceTable::new(),
        }
    }
}

// ─── host interface impl (store data is the host; traits are generated by the bindgen macro, synchronous methods) ────────

/// host-transport: connection handles live in store data; I/O is performed by the host.
/// Uses `std::net::TcpStream` (synchronous blocking + read/write timeout) to avoid block_on of another runtime in async/sync calls, which panics.
impl orbit::protocol_plugin::host_transport::Host for ProtocolHostState {
    fn connect(&mut self, target: String, _options: String) -> Result<u32, String> {
        // options reserved: TLS/connection parameters (phase 2)
        use std::net::TcpStream;
        let stream =
            TcpStream::connect(&target).map_err(|e| format!("connect {}: {}", target, e))?;
        stream.set_read_timeout(Some(DEFAULT_SOCKET_TIMEOUT)).ok();
        stream.set_write_timeout(Some(DEFAULT_SOCKET_TIMEOUT)).ok();
        self.next_conn += 1;
        self.conns.insert(self.next_conn, stream);
        Ok(self.next_conn)
    }
    fn send(&mut self, conn: u32, data: Vec<u8>) -> Result<(), String> {
        use std::io::Write as _;
        let stream = self
            .conns
            .remove(&conn)
            .ok_or_else(|| format!("conn {} not open", conn))?;
        let result = stream
            .try_clone()
            .map_err(|e| e.to_string())
            .and_then(|mut s| {
                s.write_all(&data).map_err(|e| e.to_string())?;
                Ok(s)
            });
        match result {
            Ok(s) => {
                self.conns.insert(conn, s);
                Ok(())
            }
            Err(e) => {
                self.conns.remove(&conn);
                Err(e)
            }
        }
    }
    fn recv(&mut self, conn: u32, max_bytes: u64) -> Result<Vec<u8>, String> {
        use std::io::Read as _;
        let stream = self
            .conns
            .remove(&conn)
            .ok_or_else(|| format!("conn {} not open", conn))?;
        let result = stream
            .try_clone()
            .map_err(|e| e.to_string())
            .and_then(|mut s| {
                let mut buf = vec![0u8; max_bytes.clamp(1, 1 << 20) as usize];
                let n = s.read(&mut buf).map_err(|e| e.to_string())?;
                buf.truncate(n);
                Ok::<_, String>((s, buf))
            });
        match result {
            Ok((s, buf)) => {
                self.conns.insert(conn, s);
                Ok(buf)
            }
            Err(e) => Err(e),
        }
    }
    fn close(&mut self, conn: u32) -> Result<(), String> {
        self.conns
            .remove(&conn)
            .map(|_| ())
            .ok_or_else(|| format!("conn {} not open", conn))
    }
}

/// host-metrics: to be wired to orbit-metrics sampling in phase 2; currently an empty impl
impl orbit::protocol_plugin::host_metrics::Host for ProtocolHostState {
    fn record_sample(
        &mut self,
        _conn: u32,
        _send_ms: u64,
        _ttfb_ms: u64,
        _receive_ms: u64,
    ) -> Result<(), String> {
        Ok(())
    }
}

/// host-log: tracing output
impl orbit::protocol_plugin::host_log::Host for ProtocolHostState {
    fn log(&mut self, level: String, message: String) {
        match level.as_str() {
            "error" => tracing::error!("[wasm-protocol] {}", message),
            "warn" => tracing::warn!("[wasm-protocol] {}", message),
            "debug" => tracing::debug!("[wasm-protocol] {}", message),
            _ => tracing::info!("[wasm-protocol] {}", message),
        }
    }
}

// ─── Instantiation ────────────────────────────────────────

/// Create a component-model engine (synchronous; protocol world interfaces are sync functions, host-transport is sync-blocking + timeout)
pub fn new_engine() -> Result<Engine, String> {
    let mut config = Config::new();
    config.wasm_component_model(true);
    Engine::new(&config).map_err(|e| format!("wasmtime engine: {}", e))
}

/// Load a component from bytes
pub fn load_component(engine: &Engine, bytes: &[u8]) -> Result<Component, String> {
    Component::from_binary(engine, bytes).map_err(|e| format!("wasm component: {}", e))
}

/// Instantiate the protocol plugin (binds host imports, returns store+instance).
pub fn instantiate(
    engine: &Engine,
    component: &Component,
) -> Result<(Store<ProtocolHostState>, ProtocolPlugin), String> {
    let mut store = Store::new(engine, ProtocolHostState::new());
    let mut linker = Linker::<ProtocolHostState>::new(engine);
    wasmtime_wasi::p2::add_to_linker_sync(&mut linker).map_err(|e| format!("link wasi: {}", e))?;
    ProtocolPlugin::add_to_linker::<ProtocolHostState, ProtocolHostState>(&mut linker, |s| s)
        .map_err(|e| e.to_string())?;
    let instance = ProtocolPlugin::instantiate(&mut store, component, &linker)
        .map_err(|e| format!("instantiate protocol plugin: {}", e))?;
    Ok((store, instance))
}

/// Shared protocol plugin instance (execute runs serially; concurrent load-test scenario optimized in phase 2)
pub struct ProtocolPluginShared {
    pub store: Store<ProtocolHostState>,
    pub instance: ProtocolPlugin,
}

/// WasmProtocolClient: bridges the orbit-protocol ProtocolClient trait -> wasm plugin execute.
pub struct WasmProtocolClient {
    pub protocol_id: String,
    pub display_name: String,
    pub streaming: bool,
    pub shared: Arc<tokio::sync::Mutex<ProtocolPluginShared>>,
}

fn map_timing_ms(ms: Option<u64>) -> Option<std::time::Duration> {
    ms.map(std::time::Duration::from_millis)
}

#[async_trait::async_trait]
impl orbit_protocol::traits::ProtocolClient for WasmProtocolClient {
    fn name(&self) -> &str {
        &self.protocol_id
    }
    fn description(&self) -> &str {
        &self.display_name
    }
    fn supports_streaming(&self) -> bool {
        self.streaming
    }
    fn clone_client(&self) -> Box<dyn orbit_protocol::traits::ProtocolClient> {
        Box::new(Self {
            protocol_id: self.protocol_id.clone(),
            display_name: self.display_name.clone(),
            streaming: self.streaming,
            shared: self.shared.clone(),
        })
    }

    async fn execute(
        &mut self,
        request: orbit_protocol::types::ProtocolRequest,
    ) -> Result<orbit_protocol::types::ProtocolResponse, orbit_protocol::types::ProtocolError> {
        let mut guard = self.shared.lock().await;
        let wit_req = crate::wasm::protocol::exports::orbit::protocol_plugin::protocol::Request {
            target: request.target,
            operation: request.operation,
            metadata: request.metadata,
            payload: request.payload,
            timeout_ms: request.timeout.map(|d| d.as_millis() as u64),
            options: serde_json::to_string(&request.options).ok(),
            connection: request.connection.clone(),
        };
        let ProtocolPluginShared { store, instance } = &mut *guard;
        let result = instance
            .orbit_protocol_plugin_protocol()
            .call_execute(store, &wit_req)
            .map_err(|e| {
                orbit_protocol::types::ProtocolError::Protocol(format!("wasm execute: {}", e))
            })?;
        let resp = result.map_err(orbit_protocol::types::ProtocolError::Protocol)?;
        Ok(orbit_protocol::types::ProtocolResponse {
            status_code: resp.status_code as i32,
            metadata: resp.metadata,
            payload: resp.payload,
            message_count: 0,
            timings: orbit_protocol::types::ProtocolTimings {
                dns: map_timing_ms(resp.timings.dns_ms),
                tcp: map_timing_ms(resp.timings.tcp_ms),
                tls: map_timing_ms(resp.timings.tls_ms),
                send: map_timing_ms(resp.timings.send_ms),
                first_byte: map_timing_ms(resp.timings.ttfb_ms),
                receive: map_timing_ms(resp.timings.receive_ms),
                total: std::time::Duration::from_millis(resp.timings.total_ms),
            },
        })
    }
}
