// gRPC request body auto-generation: from the message schema (`{ properties }` returned by `message_schema`)
// it uses the backend orbit-dynamic engine to generate random values by field name / type, matching the HTTP auto-generation experience.

import { generateDynamicValue } from "@/lib/bridge/request";

/** Field description in a gRPC schema (generated by the backend message_schema) */
interface GrpcFieldSchema {
  type?: string;
  example?: unknown;
  properties?: { properties?: Record<string, GrpcFieldSchema> };
  items?: { properties?: Record<string, GrpcFieldSchema> };
  additionalProperties?: Record<string, GrpcFieldSchema> | string;
}

/** Generate a string dynamic value */
function dvStr(
  category: string,
  method: string,
  args?: string,
): Promise<string> {
  return generateDynamicValue(category, method, args);
}

/** Generate a numeric dynamic value (the backend returns a string, converted by field type) */
async function dvNumber(
  category: string,
  method: string,
  min: number,
  max: number,
): Promise<number> {
  const s = await dvStr(category, method, `min=${min}, max=${max}`);
  const n = parseFloat(s);
  return Number.isNaN(n) ? min : n;
}

/** Generate a boolean */
async function dvBool(): Promise<boolean> {
  return (await dvStr("datatype", "boolean")) === "true";
}

/** Infer more meaningful fake data from field-name keywords (aligned with the HTTP generate.ts) */
function byName(name: string): (() => Promise<unknown>) | null {
  const n = name.toLowerCase();
  if (/(^|_)id$|uuid|guid/.test(n)) {
    return /uuid|guid/.test(n)
      ? () => dvStr("string", "uuid")
      : () => dvNumber("number", "int", 1, 100000);
  }
  if (/email/.test(n)) return () => dvStr("internet", "email");
  if (/(user_?name|login|account)/.test(n))
    return () => dvStr("internet", "userName");
  if (/(first|last)?name/.test(n)) return () => dvStr("person", "fullName");
  if (/phone|mobile|tel/.test(n)) return () => dvStr("phone", "number");
  if (/password|passwd|pwd/.test(n))
    return () => dvStr("internet", "password", "length=12");
  if (/token|secret|apikey|api_key/.test(n))
    return () => dvStr("string", "alphanumeric", "length=32");
  if (/avatar|image|img|photo|picture/.test(n))
    return () => dvStr("image", "avatar");
  if (/url|link|href|website/.test(n)) return () => dvStr("internet", "url");
  if (/(^ip$|ip_?addr|ip_address)/.test(n))
    return () => dvStr("internet", "ip");
  if (/color|colour/.test(n)) return () => dvStr("color", "name");
  if (/(city|town)/.test(n)) return () => dvStr("location", "city");
  if (/(address|street)/.test(n)) return () => dvStr("location", "address");
  if (/(country|region)/.test(n)) return () => dvStr("location", "country");
  if (/(price|amount|cost|fee|total|sum|money|salary)/.test(n))
    return () => dvStr("commerce", "price");
  if (/(count|quantity|qty|stock|num|number)/.test(n))
    return () => dvNumber("number", "int", 1, 100);
  if (/(date|time|created|updated|at$)/.test(n))
    return () => dvStr("date", "pastRandom", "days=30");
  if (
    /description|remark|comment|note|summary|title|content|text|bio|message/.test(
      n,
    )
  )
    return () => dvStr("lorem", "sentence");
  if (/status/.test(n))
    return () =>
      dvStr("helpers", "arrayElement", "active, inactive, pending, disabled");
  if (/gender|sex/.test(n))
    return () => dvStr("helpers", "arrayElement", "male, female, other");
  if (/age/.test(n)) return () => dvNumber("number", "int", 18, 80);
  if (/code|sku/.test(n))
    return async () =>
      (await dvStr("string", "alphanumeric", "length=8")).toUpperCase();
  return null;
}

async function genObject(
  props?: Record<string, GrpcFieldSchema>,
): Promise<Record<string, unknown>> {
  const obj: Record<string, unknown> = {};
  if (props) {
    for (const [name, field] of Object.entries(props)) {
      obj[name] = await genField(name, field);
    }
  }
  return obj;
}

async function genField(
  name: string,
  field: GrpcFieldSchema,
): Promise<unknown> {
  const type = (field.type ?? "string").toLowerCase();

  // Array: recursively generate 1-3 items from `items`
  if (type.endsWith("[]")) {
    const itemSchema = field.items?.properties
      ? { type: "object", properties: field.items.properties }
      : { type: type.slice(0, -2) };
    const len = await dvNumber("number", "int", 1, 3);
    const out: unknown[] = [];
    for (let i = 0; i < len; i++) {
      out.push(await genField(name, itemSchema));
    }
    return out;
  }

  // map: recursively generate one key/value pair from additionalProperties
  if (type.startsWith("map<")) {
    const key = await dvStr("lorem", "word");
    const valSchema: GrpcFieldSchema =
      field.additionalProperties &&
      typeof field.additionalProperties === "object"
        ? { type: "object", properties: field.additionalProperties }
        : {
            type:
              typeof field.additionalProperties === "string"
                ? field.additionalProperties
                : "string",
          };
    return { [key]: await genField(name, valSchema) };
  }

  // Nested message object
  if (type === "object") {
    return genObject(field.properties);
  }

  // Use the example value when present (e.g. the first enum value)
  if (field.example !== undefined && field.example !== "") {
    return field.example;
  }

  // Infer from the name
  const byNameFn = byName(name);
  if (byNameFn) return byNameFn();

  // Generate by type
  switch (type) {
    case "string":
      return dvStr("lorem", "words", "count=2");
    case "integer":
      return dvNumber("number", "int", 0, 1000);
    case "number":
      return dvNumber("number", "float", 0, 1000);
    case "boolean":
      return dvBool();
    case "bytes":
      return dvStr("string", "alphanumeric", "length=16");
    case "enum":
      return field.example ?? (await dvStr("lorem", "word"));
    default:
      return null;
  }
}

/** Generate a formatted sample JSON request body string from the message schema. */
export async function generateGrpcBody(
  schema: { properties: Record<string, unknown> } | null | undefined,
): Promise<string> {
  const obj = await genObject(
    schema?.properties as Record<string, GrpcFieldSchema> | undefined,
  );
  return JSON.stringify(obj, null, 2);
}
