/**
 * Dynamic value definitions and template resolution.
 *
 * Every dynamic value is generated by calling the real Rust backend (orbit_dynamic) through the bridge.
 * Template syntax: {{key}} = variable, {{$category.method(args)}} = dynamic value.
 */
import type { DataLocale, HttpRequest, KeyValue } from "@/data/types";

export type Locale = "zh-CN" | "en-US";

export interface DynamicDef {
  category: string;
  method: string;
  /** i18n key of the display label */
  labelKey: string;
  args?: string;
  /** i18n key of the description */
  descKey: string;
  /** Whether every argument is optional (the backend default is used when omitted) */
  argsOptional?: boolean;
  /** i18n key of the default-value note (e.g. "format=yyyy-MM-dd HH:mm:ss"), shown when argsOptional */
  defaultsKey?: string;
  /** Time zone shown in the reference dialog examples (e.g. "Asia/Shanghai"), used by parameterized date entries */
  tzExample?: string;
  /** Locale-sensitive: the output varies with locale (zh/en/ja) and a `locale=` argument is appended when inserting */
  localeSensitive?: boolean;
}

/**
 * Dynamic value catalog aligned with the backend orbit_dynamic (19 categories / 55 curated methods).
 *
 * Labels and descriptions live in the locale files; the keys follow
 * `dyn.<category>.<method>.{label,desc}` (plus `.defaults` when argsOptional).
 */
export const DYNAMIC_CATALOG: DynamicDef[] = [
  // ── string ──
  {
    category: "string",
    method: "uuid",
    labelKey: "dyn.string.uuid.label",
    descKey: "dyn.string.uuid.desc",
  },
  {
    category: "string",
    method: "alpha",
    labelKey: "dyn.string.alpha.label",
    args: "length=10",
    descKey: "dyn.string.alpha.desc",
    argsOptional: true,
    defaultsKey: "dyn.string.alpha.defaults",
  },
  {
    category: "string",
    method: "alphanumeric",
    labelKey: "dyn.string.alphanumeric.label",
    args: "length=10",
    descKey: "dyn.string.alphanumeric.desc",
    argsOptional: true,
    defaultsKey: "dyn.string.alphanumeric.defaults",
  },
  {
    category: "string",
    method: "numeric",
    labelKey: "dyn.string.numeric.label",
    args: "length=10",
    descKey: "dyn.string.numeric.desc",
    argsOptional: true,
    defaultsKey: "dyn.string.numeric.defaults",
  },

  // ── number ──
  {
    category: "number",
    method: "int",
    labelKey: "dyn.number.int.label",
    args: "min=0, max=100",
    descKey: "dyn.number.int.desc",
    argsOptional: true,
    defaultsKey: "dyn.number.int.defaults",
  },
  {
    category: "number",
    method: "float",
    labelKey: "dyn.number.float.label",
    args: "min=0, max=100, decimals=2",
    descKey: "dyn.number.float.desc",
    argsOptional: true,
    defaultsKey: "dyn.number.float.defaults",
  },
  {
    category: "number",
    method: "hex",
    labelKey: "dyn.number.hex.label",
    args: "min=0, max=255",
    descKey: "dyn.number.hex.desc",
    argsOptional: true,
    defaultsKey: "dyn.number.hex.defaults",
  },

  // ── date ──
  // Note: every date method accepts an optional `tz` argument (an IANA name such as Asia/Shanghai, UTC, or a fixed offset like +08:00); it defaults to the local time zone.
  {
    category: "date",
    method: "now",
    labelKey: "dyn.date.now.label",
    args: "format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.now.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.now.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "time",
    labelKey: "dyn.date.time.label",
    args: "format=HH:mm:ss",
    descKey: "dyn.date.time.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.time.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "timestamp",
    labelKey: "dyn.date.timestamp.label",
    descKey: "dyn.date.timestamp.desc",
  },
  {
    category: "date",
    method: "timestampMs",
    labelKey: "dyn.date.timestampMs.label",
    descKey: "dyn.date.timestampMs.desc",
  },
  {
    category: "date",
    method: "today",
    labelKey: "dyn.date.today.label",
    args: "format=yyyy-MM-dd",
    descKey: "dyn.date.today.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.today.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "iso",
    labelKey: "dyn.date.iso.label",
    descKey: "dyn.date.iso.desc",
  },
  {
    category: "date",
    method: "isoDate",
    labelKey: "dyn.date.isoDate.label",
    args: "format=yyyy-MM-dd",
    descKey: "dyn.date.isoDate.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.isoDate.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "offset",
    labelKey: "dyn.date.offset.label",
    args: "unit=days, amount=-7, format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.offset.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.offset.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "past",
    labelKey: "dyn.date.past.label",
    args: "unit=days, amount=30, format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.past.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.past.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "future",
    labelKey: "dyn.date.future.label",
    args: "unit=days, amount=30, format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.future.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.future.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "random",
    labelKey: "dyn.date.random.label",
    args: "format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.random.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.random.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "between",
    labelKey: "dyn.date.between.label",
    args: "start=2024-01-01, end=2024-12-31, format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.between.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.between.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "pastRandom",
    labelKey: "dyn.date.pastRandom.label",
    args: "days=30, format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.pastRandom.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.pastRandom.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "futureRandom",
    labelKey: "dyn.date.futureRandom.label",
    args: "days=30, format=yyyy-MM-dd HH:mm:ss",
    descKey: "dyn.date.futureRandom.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.futureRandom.defaults",
    tzExample: "Asia/Shanghai",
  },
  {
    category: "date",
    method: "weekday",
    labelKey: "dyn.date.weekday.label",
    args: "format=EEEE",
    descKey: "dyn.date.weekday.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.weekday.defaults",
    tzExample: "Asia/Shanghai",
    localeSensitive: true,
  },
  {
    category: "date",
    method: "monthName",
    labelKey: "dyn.date.monthName.label",
    args: "format=MMMM",
    descKey: "dyn.date.monthName.desc",
    argsOptional: true,
    defaultsKey: "dyn.date.monthName.defaults",
    tzExample: "Asia/Shanghai",
    localeSensitive: true,
  },
  {
    category: "date",
    method: "year",
    labelKey: "dyn.date.year.label",
    descKey: "dyn.date.year.desc",
  },
  {
    category: "date",
    method: "month",
    labelKey: "dyn.date.month.label",
    descKey: "dyn.date.month.desc",
  },
  {
    category: "date",
    method: "day",
    labelKey: "dyn.date.day.label",
    descKey: "dyn.date.day.desc",
  },
  {
    category: "date",
    method: "hour",
    labelKey: "dyn.date.hour.label",
    descKey: "dyn.date.hour.desc",
  },
  {
    category: "date",
    method: "minute",
    labelKey: "dyn.date.minute.label",
    descKey: "dyn.date.minute.desc",
  },
  {
    category: "date",
    method: "second",
    labelKey: "dyn.date.second.label",
    descKey: "dyn.date.second.desc",
  },
  {
    category: "date",
    method: "timeZone",
    labelKey: "dyn.date.timeZone.label",
    descKey: "dyn.date.timeZone.desc",
  },

  // ── person ──
  {
    category: "person",
    method: "fullName",
    labelKey: "dyn.person.fullName.label",
    descKey: "dyn.person.fullName.desc",
    localeSensitive: true,
  },
  {
    category: "person",
    method: "firstName",
    labelKey: "dyn.person.firstName.label",
    descKey: "dyn.person.firstName.desc",
    localeSensitive: true,
  },
  {
    category: "person",
    method: "lastName",
    labelKey: "dyn.person.lastName.label",
    descKey: "dyn.person.lastName.desc",
    localeSensitive: true,
  },
  {
    category: "person",
    method: "idCard",
    labelKey: "dyn.person.idCard.label",
    descKey: "dyn.person.idCard.desc",
  },
  {
    category: "person",
    method: "gender",
    labelKey: "dyn.person.gender.label",
    descKey: "dyn.person.gender.desc",
    localeSensitive: true,
  },
  {
    category: "person",
    method: "age",
    labelKey: "dyn.person.age.label",
    args: "min=18, max=80",
    descKey: "dyn.person.age.desc",
    argsOptional: true,
    defaultsKey: "dyn.person.age.defaults",
  },

  // ── internet ──
  {
    category: "internet",
    method: "email",
    labelKey: "dyn.internet.email.label",
    descKey: "dyn.internet.email.desc",
  },
  {
    category: "internet",
    method: "url",
    labelKey: "dyn.internet.url.label",
    descKey: "dyn.internet.url.desc",
  },
  {
    category: "internet",
    method: "ip",
    labelKey: "dyn.internet.ip.label",
    descKey: "dyn.internet.ip.desc",
  },
  {
    category: "internet",
    method: "userName",
    labelKey: "dyn.internet.userName.label",
    descKey: "dyn.internet.userName.desc",
  },
  {
    category: "internet",
    method: "password",
    labelKey: "dyn.internet.password.label",
    args: "length=12",
    descKey: "dyn.internet.password.desc",
    argsOptional: true,
    defaultsKey: "dyn.internet.password.defaults",
  },
  {
    category: "internet",
    method: "userAgent",
    labelKey: "dyn.internet.userAgent.label",
    descKey: "dyn.internet.userAgent.desc",
  },

  // ── phone ──
  {
    category: "phone",
    method: "mobile",
    labelKey: "dyn.phone.mobile.label",
    descKey: "dyn.phone.mobile.desc",
    localeSensitive: true,
  },

  // ── location ──
  {
    category: "location",
    method: "city",
    labelKey: "dyn.location.city.label",
    descKey: "dyn.location.city.desc",
    localeSensitive: true,
  },
  {
    category: "location",
    method: "address",
    labelKey: "dyn.location.address.label",
    descKey: "dyn.location.address.desc",
    localeSensitive: true,
  },
  {
    category: "location",
    method: "zipCode",
    labelKey: "dyn.location.zipCode.label",
    descKey: "dyn.location.zipCode.desc",
  },

  // ── commerce ──
  {
    category: "commerce",
    method: "price",
    labelKey: "dyn.commerce.price.label",
    descKey: "dyn.commerce.price.desc",
  },
  {
    category: "commerce",
    method: "productName",
    labelKey: "dyn.commerce.productName.label",
    descKey: "dyn.commerce.productName.desc",
    localeSensitive: true,
  },
  {
    category: "commerce",
    method: "sku",
    labelKey: "dyn.commerce.sku.label",
    descKey: "dyn.commerce.sku.desc",
  },

  // ── company ──
  {
    category: "company",
    method: "name",
    labelKey: "dyn.company.name.label",
    descKey: "dyn.company.name.desc",
    localeSensitive: true,
  },

  // ── finance ──
  {
    category: "finance",
    method: "accountNumber",
    labelKey: "dyn.finance.accountNumber.label",
    args: "length=16",
    descKey: "dyn.finance.accountNumber.desc",
    argsOptional: true,
    defaultsKey: "dyn.finance.accountNumber.defaults",
  },
  {
    category: "finance",
    method: "amount",
    labelKey: "dyn.finance.amount.label",
    args: "min=1, max=99999",
    descKey: "dyn.finance.amount.desc",
    argsOptional: true,
    defaultsKey: "dyn.finance.amount.defaults",
  },
  {
    category: "finance",
    method: "currencyCode",
    labelKey: "dyn.finance.currencyCode.label",
    descKey: "dyn.finance.currencyCode.desc",
  },

  // ── helpers ──
  {
    category: "helpers",
    method: "rangeToNumber",
    labelKey: "dyn.helpers.rangeToNumber.label",
    args: "min=1, max=100",
    descKey: "dyn.helpers.rangeToNumber.desc",
    argsOptional: true,
    defaultsKey: "dyn.helpers.rangeToNumber.defaults",
  },
  {
    category: "helpers",
    method: "arrayElement",
    labelKey: "dyn.helpers.arrayElement.label",
    args: "a,b,c",
    descKey: "dyn.helpers.arrayElement.desc",
  },

  // ── datatype ──
  {
    category: "datatype",
    method: "boolean",
    labelKey: "dyn.datatype.boolean.label",
    descKey: "dyn.datatype.boolean.desc",
  },

  // ── image ──
  {
    category: "image",
    method: "url",
    labelKey: "dyn.image.url.label",
    args: "width=300, height=300",
    descKey: "dyn.image.url.desc",
    argsOptional: true,
    defaultsKey: "dyn.image.url.defaults",
  },
  {
    category: "image",
    method: "avatar",
    labelKey: "dyn.image.avatar.label",
    args: "width=200",
    descKey: "dyn.image.avatar.desc",
    argsOptional: true,
    defaultsKey: "dyn.image.avatar.defaults",
  },

  // ── lorem ──
  {
    category: "lorem",
    method: "sentence",
    labelKey: "dyn.lorem.sentence.label",
    descKey: "dyn.lorem.sentence.desc",
    localeSensitive: true,
  },
  {
    category: "lorem",
    method: "paragraph",
    labelKey: "dyn.lorem.paragraph.label",
    descKey: "dyn.lorem.paragraph.desc",
    localeSensitive: true,
  },

  // ── color ──
  {
    category: "color",
    method: "name",
    labelKey: "dyn.color.name.label",
    descKey: "dyn.color.name.desc",
    localeSensitive: true,
  },
  {
    category: "color",
    method: "hex",
    labelKey: "dyn.color.hex.label",
    descKey: "dyn.color.hex.desc",
  },
  {
    category: "color",
    method: "rgb",
    labelKey: "dyn.color.rgb.label",
    descKey: "dyn.color.rgb.desc",
  },

  // ── food ──
  {
    category: "food",
    method: "dish",
    labelKey: "dyn.food.dish.label",
    descKey: "dyn.food.dish.desc",
    localeSensitive: true,
  },

  // ── vehicle ──
  {
    category: "vehicle",
    method: "brand",
    labelKey: "dyn.vehicle.brand.label",
    descKey: "dyn.vehicle.brand.desc",
    localeSensitive: true,
  },

  // ── music ──
  {
    category: "music",
    method: "songName",
    labelKey: "dyn.music.songName.label",
    descKey: "dyn.music.songName.desc",
    localeSensitive: true,
  },
  {
    category: "music",
    method: "artist",
    labelKey: "dyn.music.artist.label",
    descKey: "dyn.music.artist.desc",
    localeSensitive: true,
  },
];

// ── Dynamic value token construction ───────────────────────────────

/**
 * Build a dynamic value token: locale-sensitive entries append a `locale=` argument for a non-zh data locale.
 * Nothing is appended for the default zh (the backend defaults to zh, keeping tokens short).
 *
 * Example: `fullName` + dataLocale="ja" → `$person.fullName(locale=ja)`
 */
export function buildDynamicToken(
  d: DynamicDef,
  dataLocale: DataLocale = "zh",
): string {
  const localeArg =
    d.localeSensitive && dataLocale !== "zh" ? `locale=${dataLocale}` : null;
  const args = [d.args, localeArg].filter(Boolean).join(", ");
  return args
    ? `$${d.category}.${d.method}(${args})`
    : `$${d.category}.${d.method}`;
}

// ── Dynamic template resolution ───────────────────────────────────

/**
 * Convert `key=value, key2=value2` arguments into the comma-separated string the backend expects.
 * The backend orbit_dynamic parses them with `parse_args`, whose separator is `,`.
 */
function formatArgs(args?: string): string {
  return (args ?? "").trim();
}

/**
 * Asynchronously resolve a template: handle `{{$category.method(args)}}` first (through the bridge to the real backend),
 * then substitute `{{key}}` (environment variables / extracted variables).
 *
 * @param keepDynamic when true, skip the first dynamic-value pass and keep `{{$...}}` verbatim —
 *   used by load tests / scenarios: the backend engine regenerates the value on every request, so all requests do not share one value.
 */
export async function resolveTemplate(
  input: string,
  variables: Record<string, string>,
  _locale: Locale = "zh-CN",
  keepDynamic = false,
): Promise<string> {
  if (!input) return input;

  let result = input;

  // First pass: resolve {{$category.method(args)}} → call the real backend (skipped when keepDynamic,
  // keeping the text for the backend to regenerate per request)
  if (!keepDynamic) {
    // Dynamic import avoids a circular dependency
    const {
      generateDynamicValue: bridgeGen,
      resolveDynamicValues: bridgeResolve,
    } = await import("./bridge");
    // Captures `|` pipes (the pipeline segments are executed entirely on the Rust side)
    const dynamicPattern =
      /\{\{\s*\$([\w-]+)\.([\w-]+)(?:\(([^)]*)\))?(?:\|([^}]+))?\s*\}\}/g;
    const dynamicMatches = [...input.matchAll(dynamicPattern)];

    // When any token has a pipe, hand the whole string to the Rust resolver (keeping pipe and multi-token semantics consistent)
    const hasPipes = dynamicMatches.some((m) => m[4]);
    if (hasPipes) {
      try {
        result = await bridgeResolve(input);
      } catch {
        console.warn(
          "[resolve] failed to resolve a dynamic value (with pipes); keeping the original text",
        );
      }
      return result.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (_m, varName) => {
        return variables[varName] ?? "";
      });
    }

    for (const m of dynamicMatches) {
      const [full, cat, meth, rawArgs] = m;
      try {
        const value = await bridgeGen(cat, meth, formatArgs(rawArgs));
        result = result.replace(full, value);
      } catch {
        // Keep the placeholder verbatim when the backend call fails
        console.warn(
          `[resolve] dynamic value generation failed: $${cat}.${meth}(${rawArgs ?? ""})`,
        );
      }
    }
  }

  // Second pass: resolve {{key}} → variable substitution
  result = result.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (_m, varName) => {
    return variables[varName] ?? "";
  });

  return result;
}

/**
 * Synchronous template resolution (variable substitution only, no dynamic values).
 * Used by simple cases that need no dynamic values.
 */
export function resolveVariables(
  input: string,
  variables: Record<string, string>,
): string {
  if (!input) return input;
  return input.replace(/\{\{\s*([\w.-]+)\s*\}\}/g, (_m, varName) => {
    return variables[varName] ?? "";
  });
}

/**
 * Extract path parameter names from a URL (`{name}` single-brace placeholders).
 * `{{...}}` templates are removed first (so the inner brace of `{{var}}` is not mistaken for one),
 * then single braces are matched; consecutive placeholders such as `{a}-{b}` are recognized too.
 */
export function extractPathParamNames(url: string): string[] {
  const noTemplates = url.replace(/\{\{[^{}]*\}\}/g, "");
  const names: string[] = [];
  const re = /\{([^{}]+)\}/g;
  for (const m of noTemplates.matchAll(re)) {
    const n = m[1].trim();
    if (n) names.push(n);
  }
  return [...new Set(names)];
}

/**
 * Resolve a URL and apply path parameters: resolve the template first, then replace each `{name}` placeholder with
 * the matching pathParams value (only non-empty values are substituted and encodeURIComponent-ed; empty values keep the placeholder).
 * @param keepDynamic when true, keep `{{$...}}` dynamic values verbatim (generated by the backend per request)
 */
export async function applyPathParams(
  url: string,
  pathParams: KeyValue[] | undefined,
  variables: Record<string, string>,
  locale: Locale = "zh-CN",
  keepDynamic = false,
): Promise<string> {
  let u = await resolveTemplate(url, variables, locale, keepDynamic);
  for (const p of pathParams ?? []) {
    if (!p.enabled || !p.key) continue;
    const v = await resolveTemplate(p.value, variables, locale, keepDynamic);
    if (v) {
      // No encoding happens when keeping dynamic values ({{$...}}) verbatim: encoding would corrupt placeholders containing % and the like,
      // so the backend resolves them per request instead
      const isDynamic = keepDynamic && v.includes("{{$");
      u = u.split(`{${p.key}}`).join(isDynamic ? v : encodeURIComponent(v));
    }
  }
  return u;
}

// ── Request URL building (shared by one-off sends / load tests / scenario YAML / request detail views) ───────

/** Join query parameter key/value pairs.
 *  With `keepDynamic` true (load tests / scenario YAML), `{{$...}}` dynamic values are not encoded
 *  — a placeholder contains characters such as %, which encoding would corrupt, so the backend engine resolves it per request. */
function joinQuery(
  url: string,
  pairs: { k: string; v: string }[],
  keepDynamic: boolean,
): string {
  if (pairs.length === 0) return url;
  const enc = (s: string) =>
    keepDynamic && s.includes("{{$") ? s : encodeURIComponent(s);
  const qs = pairs.map((p) => `${enc(p.k)}=${enc(p.v)}`).join("&");
  return url + (url.includes("?") ? "&" : "?") + qs;
}

/**
 * Build the final request URL: URL template resolution + path parameters + query parameter joining.
 * Shared by one-off debugging / load tests / the "Request" tab detail view so what is shown matches what is really sent.
 *
 * @param keepDynamic when true, keep `{{$...}}` dynamic values verbatim (load tests: regenerated by the backend per request)
 */
export async function buildRequestUrl(
  req: Pick<HttpRequest, "url" | "pathParams" | "queryParams">,
  variables: Record<string, string>,
  locale: Locale = "zh-CN",
  keepDynamic = false,
): Promise<string> {
  let url = await applyPathParams(
    req.url,
    req.pathParams,
    variables,
    locale,
    keepDynamic,
  );
  const enabledParams = (req.queryParams ?? []).filter(
    (p) => p.enabled && p.key,
  );
  const pairs = await Promise.all(
    enabledParams.map(async (p) => ({
      k: await resolveTemplate(p.key, variables, locale, keepDynamic),
      v: await resolveTemplate(p.value, variables, locale, keepDynamic),
    })),
  );
  return joinQuery(url, pairs, keepDynamic);
}

/**
 * Structural URL building (for scenario YAML): only path / query parameter joining,
 * **without resolving variables** — `{{var}}` / `{{$...}}` placeholders stay verbatim in the YAML and
 * are interpolated by the backend engine on every request (pipeline.interp_value normalizes `{{var}}` → `${var}`,
 * with missing variables left as-is).
 *
 * Encoding heuristic: literal values are encodeURIComponent-ed, while placeholder values containing `{{` are left alone
 * (a placeholder contains characters such as `{ } %`, which encoding would corrupt, so the engine resolves it).
 */
export function buildRequestUrlRaw(
  req: Pick<HttpRequest, "url" | "pathParams" | "queryParams">,
): string {
  const isPlaceholder = (s: string) => s.includes("{{");
  let url = req.url;
  for (const p of req.pathParams ?? []) {
    if (!p.enabled || !p.key) continue;
    const v = p.value ?? "";
    if (v) {
      url = url
        .split(`{${p.key}}`)
        .join(isPlaceholder(v) ? v : encodeURIComponent(v));
    }
  }
  const enabledParams = (req.queryParams ?? []).filter(
    (p) => p.enabled && p.key,
  );
  if (enabledParams.length === 0) return url;
  const enc = (s: string) => (isPlaceholder(s) ? s : encodeURIComponent(s));
  const qs = enabledParams
    .map((p) => `${enc(p.key)}=${enc(p.value)}`)
    .join("&");
  return url + (url.includes("?") ? "&" : "?") + qs;
}
