[package]
name = "orbit-extractor"
version.workspace = true
license.workspace = true
edition = "2021"
repository = "https://github.com/chenx-io/orbit"
description = "Variable extraction engine for Orbit"

[dependencies]
orbit-codec = { path = "../orbit-codec" }
serde_json.workspace = true
regex.workspace = true
jmespath.workspace = true
thiserror.workspace = true
