//! Unified import/export intermediate representation (IR) - protocol-agnostic
//!
//! Every importer only does "source text -> ApiSpec"; exporters and the two use cases are derived by the framework:
//! - [`From<ApiSpec> for TestPlan`]: scenario import (all protocols)
//! - [`From<ApiSpec> for ImportParseResult`]: endpoint import (HTTP display model)
//!
//! Design notes:
//! - the request carrier reuses [`RequestSpec`] directly (Orbit domain model, protocol-agnostic)
//! - `extensions` passes through unmodeled content, so imports lose no data and exports can rebuild it

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};
use std::collections::HashMap;

use super::endpoint::{ImportParseResult, ImportedEndpoint, ImportedResponse, ImportedSchema};
use crate::model::action::{merge_pre_actions, RequestAction};
use crate::model::check::{Check, CheckKind};
use crate::model::plan::{Executor, Scenario, TestPlan};
use crate::model::request::RequestSpec;
use crate::model::step::Step;

/// Unified import/export intermediate representation
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiSpec {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(default)]
    pub variables: HashMap<String, String>,
    #[serde(default)]
    pub endpoints: Vec<EndpointSpec>,
    /// Data models (openapi schema / proto message, etc.)
    #[serde(default)]
    pub models: Vec<ModelSpec>,
    /// Global auth (HTTP semantics only)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth: Option<AuthSpec>,
    /// Executor hint for scenario import (carried by k6/jmeter; defaults to sequential)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub executor: Option<Executor>,
    /// Source document pass-through (L3: unstructured standard fields preserved as-is, roundtrip loses no data)
    #[serde(default, skip_serializing_if = "Map::is_empty")]
    pub raw: Map<String, Value>,
    /// Unmodeled format-specific content (pass-through fallback)
    #[serde(default, skip_serializing_if = "Map::is_empty")]
    pub extensions: Map<String, Value>,
}

impl ApiSpec {
    pub fn new(name: impl Into<String>) -> Self {
        ApiSpec {
            name: name.into(),
            description: None,
            variables: HashMap::new(),
            endpoints: Vec::new(),
            models: Vec::new(),
            auth: None,
            executor: None,
            raw: Map::new(),
            extensions: Map::new(),
        }
    }
}

/// Endpoint (protocol-agnostic)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EndpointSpec {
    pub name: String,
    /// Nested directory (Postman folder hierarchy; OpenAPI tags)
    #[serde(default)]
    pub group: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Protocol-agnostic request carrier (reuses the Orbit domain model)
    pub request: RequestSpec,
    /// Auth type hint (HTTP display semantics only; no real credentials injected)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub auth: Option<AuthSpec>,
    /// Request body content-type (for HTTP display; inferred from headers by default)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    /// Name of the data model associated with the request body (for HTTP display)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_ref: Option<String>,
    /// query params (for HTTP display; appended to the url during scenario import)
    #[serde(default, skip_serializing_if = "HashMap::is_empty")]
    pub query_params: HashMap<String, String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub pre_script: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub post_script: Option<String>,
    /// **Backward-compatible read-only field (deprecated, no longer written)**: the previous version's "pre-interpolation actions" list.
    ///
    /// When converted to [`Step`] it is merged into `pre_actions` **before the built-in interpolation node** (see
    /// [`merge_pre_actions`]), ensuring the import/export roundtrip loses no semantics.
    #[serde(default, skip_serializing)]
    pub pre_resolve_actions: Vec<RequestAction>,
    /// Pre-actions list (JS scripts / database queries / built-in interpolation node; order is execution order)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pre_actions: Vec<RequestAction>,
    /// Post-actions list (internal roundtrip fidelity)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub post_actions: Vec<RequestAction>,
    /// Assertions (used during scenario import; a status check is auto-generated by default)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub checks: Vec<Check>,
    /// Pre-request wait (milliseconds; JMeter Timer semantics)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub wait_ms: Option<u64>,
    #[serde(default)]
    pub disabled: bool,
    /// Response definition (for HTTP display)
    #[serde(default)]
    pub responses: Vec<ResponseSpec>,
    #[serde(default, skip_serializing_if = "Map::is_empty")]
    pub extensions: Map<String, Value>,
}

impl EndpointSpec {
    pub fn new(name: impl Into<String>, request: RequestSpec) -> Self {
        EndpointSpec {
            name: name.into(),
            group: Vec::new(),
            description: None,
            request,
            auth: None,
            content_type: None,
            model_ref: None,
            query_params: HashMap::new(),
            pre_script: None,
            post_script: None,
            pre_resolve_actions: Vec::new(),
            pre_actions: Vec::new(),
            post_actions: Vec::new(),
            checks: Vec::new(),
            wait_ms: None,
            disabled: false,
            responses: Vec::new(),
            extensions: Map::new(),
        }
    }

    /// Request url (HTTP variant; empty for other protocols)
    pub fn url_of(&self) -> String {
        match &self.request {
            RequestSpec::Http(h) => h.url.clone(),
            _ => String::new(),
        }
    }
}

/// Auth type hint (import expresses only the type, no real credentials)
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AuthSpec {
    Bearer,
    Basic,
    ApiKey { name: String, location: String },
    OAuth2,
}

impl From<&AuthSpec> for (String, String, String) {
    /// Flattened to (auth_type, auth_key_name, auth_add_to)
    fn from(a: &AuthSpec) -> Self {
        match a {
            AuthSpec::Bearer => ("bearer".into(), String::new(), String::new()),
            AuthSpec::Basic => ("basic".into(), String::new(), String::new()),
            AuthSpec::ApiKey { name, location } => {
                ("apikey".into(), name.clone(), location.clone())
            }
            AuthSpec::OAuth2 => ("oauth2".into(), String::new(), String::new()),
        }
    }
}

/// Response definition (status code range supported, e.g. "2XX" -> status 0 + name preserved as-is)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResponseSpec {
    pub status: u16,
    pub name: String,
    pub body: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub schema: Option<Value>,
}

/// Data model (named schema)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelSpec {
    pub name: String,
    pub schema: Value,
}

// ─── Derivation: scenario import (all protocols) ───────────────────────────────

impl From<ApiSpec> for TestPlan {
    fn from(spec: ApiSpec) -> Self {
        let mut steps = Vec::new();
        for ep in spec.endpoints {
            // pre-request wait (JMeter Timer semantics)
            if let Some(ms) = ep.wait_ms {
                if ms > 0 {
                    steps.push(Step::Wait {
                        name: "wait".to_string(),
                        duration: format!("{}ms", ms),
                        disabled: false,
                    });
                }
            }
            steps.push(endpoint_to_step(ep));
        }
        let executor = spec
            .executor
            .unwrap_or(Executor::Sequential { iterations: 1 });
        TestPlan {
            name: spec.name.clone(),
            environments: Vec::new(),
            variables: spec.variables,
            datasources: Vec::new(),
            thresholds: Vec::new(),
            scenarios: vec![Scenario {
                name: format!("{} - Imported", spec.name),
                executor,
                steps,
                on_error: Default::default(),
            }],
        }
    }
}

fn endpoint_to_step(ep: EndpointSpec) -> Step {
    let name = if ep.group.is_empty() {
        ep.name.clone()
    } else {
        format!("{}/{}", ep.group.join("/"), ep.name)
    };
    let status_value = match method_of(&ep.request) {
        Some("POST") | Some("PUT") => 201,
        _ => 200,
    };
    let mut request = ep.request;
    // append query params to url (HTTP; ignored for non-HTTP)
    if let RequestSpec::Http(h) = &mut request {
        if !ep.query_params.is_empty() && !h.url.contains('?') {
            let qs = ep
                .query_params
                .iter()
                .map(|(k, v)| format!("{}={}", k, v))
                .collect::<Vec<_>>()
                .join("&");
            h.url = format!("{}?{}", h.url, qs);
        }
    }
    // assertions: use importer-specified ones (k6 check), otherwise auto-generate a status check
    let checks = if ep.checks.is_empty() {
        vec![Check {
            kind: CheckKind::Status {
                value: status_value,
            },
            meta: None,
        }]
    } else {
        ep.checks
    };
    Step::Request {
        name,
        request,
        protocol: None,
        protocol_id: None,
        checks,
        extract: Vec::new(),
        pre_script: ep.pre_script,
        post_script: ep.post_script,
        // the previous version's "pre-interpolation actions" are merged into the single list (before the anchor); the compat field is no longer passed through
        pre_resolve_actions: Vec::new(),
        pre_resolve_script: None,
        pre_actions: merge_pre_actions(&ep.pre_actions, None, &ep.pre_resolve_actions, None),
        post_actions: ep.post_actions,
        tags: ep.group,
        disabled: ep.disabled,
    }
}

/// Extract the request method (HTTP variant; None for other protocols)
pub(crate) fn method_of(request: &RequestSpec) -> Option<&str> {
    match request {
        RequestSpec::Http(h) => Some(h.method.as_str()),
        _ => None,
    }
}

// ─── Derivation: endpoint import (HTTP display model) ─────────────────────────

impl From<ApiSpec> for ImportParseResult {
    fn from(spec: ApiSpec) -> Self {
        let global_auth = spec.auth.clone();
        let endpoints = spec
            .endpoints
            .into_iter()
            .filter_map(|ep| endpoint_to_imported(ep, global_auth.as_ref()))
            .collect();
        let schemas = spec
            .models
            .into_iter()
            .map(|m| ImportedSchema {
                name: m.name,
                schema_json: m.schema,
            })
            .collect();
        ImportParseResult { endpoints, schemas }
    }
}

fn endpoint_to_imported(
    ep: EndpointSpec,
    global_auth: Option<&AuthSpec>,
) -> Option<ImportedEndpoint> {
    // the current frontend display model is HTTP-only; non-HTTP endpoints are skipped (multi-protocol import uses scenarios)
    let h = match &ep.request {
        RequestSpec::Http(h) => h.as_ref(),
        _ => return None,
    };
    // auth: endpoint level takes precedence, otherwise global (openapi global security)
    let auth = ep.auth.as_ref().or(global_auth);
    let (auth_type, auth_key_name, auth_add_to) = match auth {
        Some(a) => a.into(),
        None => ("none".into(), String::new(), String::new()),
    };
    let content_type = ep
        .content_type
        .clone()
        .or_else(|| {
            h.headers
                .iter()
                .find(|(k, _)| k.eq_ignore_ascii_case("content-type"))
                .map(|(_, v)| v.clone())
        })
        .unwrap_or_default();
    let responses = ep
        .responses
        .into_iter()
        .map(|r| ImportedResponse {
            status: r.status,
            name: r.name,
            body: r.body,
            schema: r.schema,
        })
        .collect();

    Some(ImportedEndpoint {
        name: ep.name,
        method: h.method.clone(),
        url: h.url.clone(),
        headers: h.headers.clone(),
        query_params: ep.query_params,
        body: body_to_display(&h.body),
        content_type,
        group: ep.group.join("/"),
        summary: ep.description.unwrap_or_default(),
        model_ref: ep.model_ref.unwrap_or_default(),
        auth_type,
        auth_key_name,
        auth_add_to,
        responses,
        pre_script: ep.pre_script.unwrap_or_default(),
        post_script: ep.post_script.unwrap_or_default(),
    })
}

/// Request body -> frontend display string (objects to pretty JSON; strings as-is)
pub(crate) fn body_to_display(body: &Option<serde_yaml::Value>) -> String {
    match body {
        None => String::new(),
        Some(serde_yaml::Value::String(s)) => s.clone(),
        Some(other) => serde_json::to_string_pretty(other).unwrap_or_default(),
    }
}
