// Unified entry point of the export module.
// Collection-level documents (openapi/swagger/postman) are generated by the backend orbit-data::export:
// the frontend passes only the "export range + latest snapshot", and the backend collects endpoints and assembles the ApiSpec (the old buildApiSpec moved down).
// The frontend keeps `collect` only for the export dialog's list preview (the backend does the authoritative collection).
// - types.ts  → shared types
// - collect.ts → collect endpoints / referenced data models from the collection tree (UI preview)
export type { ExportSpec, ExportFileFormat, ExportRequest } from "./types";
export { collectExportRequests, collectReferencedModels } from "./collect";

import type { ExportFileFormat, ExportSpec } from "./types";

/** Export file name (by document kind + file format). */
export function defaultFileName(
  title: string,
  spec: ExportSpec,
  format: ExportFileFormat,
): string {
  const safe =
    (title || "api")
      .replace(/[^\w\u4e00-\u9fa5.-]+/g, "_")
      .replace(/^_+|_+$/g, "") || "api";
  const specShort =
    spec === "openapi" ? "openapi" : spec === "swagger" ? "swagger" : "postman";
  return `${safe}.${specShort}.${format}`;
}
