//! gRPC Server Reflection client
//!
//! Implements the gRPC reflection protocol, supporting:
//! - List all available services (list_services)
//! - Fetch a service's FileDescriptorProto (file_containing_symbol)
//! - Describe a method signature (describe_method)
//! - Build a full service descriptor cache
//!
//! Built on prost-compiled reflection proto messages and a tonic Channel.

use std::collections::HashMap;

use prost::Message as ProstMessage;
use prost_types::FileDescriptorProto;
use tonic::transport::Channel;
use tower::Service;
use tower::ServiceExt;

use crate::grpc::encode_grpc_frame;
use crate::types::ProtocolError;

// reflection proto types generated by prost
include!(concat!(env!("OUT_DIR"), "/grpc.reflection.v1alpha.rs"));

/// Method descriptor information
#[derive(Debug, Clone)]
pub struct MethodDescriptorInfo {
    /// Fully-qualified name of the input message type (e.g. ".package.MessageName")
    pub input_type: String,
    /// Fully-qualified name of the output message type
    pub output_type: String,
    /// Whether the method is client streaming
    pub client_streaming: bool,
    /// Whether the method is server streaming
    pub server_streaming: bool,
}

/// gRPC Reflection client
#[derive(Clone)]
pub struct GrpcReflectionClient {
    channel: Channel,
}

/// Service descriptor cache
#[derive(Debug, Clone, Default)]
pub struct ServiceDescriptorCache {
    /// Service name → FileDescriptorProto bytes associated with that service
    pub file_descriptors: HashMap<String, Vec<Vec<u8>>>,
    /// "service_name/method_name" → MethodDescriptorInfo
    pub methods: HashMap<String, MethodDescriptorInfo>,
    /// List of all service names
    pub services: Vec<String>,
}

impl GrpcReflectionClient {
    /// Create a reflection client from a tonic Channel
    pub fn new(channel: Channel) -> Self {
        Self { channel }
    }

    /// List all available services
    pub async fn list_services(&mut self) -> Result<Vec<String>, ProtocolError> {
        let request = ServerReflectionRequest {
            host: String::new(),
            message_request: Some(server_reflection_request::MessageRequest::ListServices(
                String::new(),
            )),
        };

        let response = self.send_reflection_request(request).await?;

        match response.message_response {
            Some(server_reflection_response::MessageResponse::ListServicesResponse(list_resp)) => {
                Ok(list_resp.service.into_iter().map(|s| s.name).collect())
            }
            Some(server_reflection_response::MessageResponse::ErrorResponse(err)) => {
                Err(ProtocolError::Protocol(format!(
                    "Reflection error (code {}): {}",
                    err.error_code, err.error_message
                )))
            }
            _ => Err(ProtocolError::Protocol(
                "Unexpected reflection response type".into(),
            )),
        }
    }

    /// Fetch the FileDescriptorProto that contains the given symbol
    pub async fn file_containing_symbol(
        &mut self,
        symbol: &str,
    ) -> Result<Vec<Vec<u8>>, ProtocolError> {
        let request = ServerReflectionRequest {
            host: String::new(),
            message_request: Some(
                server_reflection_request::MessageRequest::FileContainingSymbol(symbol.to_string()),
            ),
        };

        let response = self.send_reflection_request(request).await?;

        match response.message_response {
            Some(server_reflection_response::MessageResponse::FileDescriptorResponse(fd_resp)) => {
                Ok(fd_resp.file_descriptor_proto)
            }
            Some(server_reflection_response::MessageResponse::ErrorResponse(err)) => {
                Err(ProtocolError::Protocol(format!(
                    "Reflection error (code {}): {}",
                    err.error_code, err.error_message
                )))
            }
            _ => Err(ProtocolError::Protocol(
                "Unexpected reflection response type".into(),
            )),
        }
    }

    /// Fetch information about the given method
    pub async fn describe_method(
        &mut self,
        service_name: &str,
        method_name: &str,
    ) -> Result<MethodDescriptorInfo, ProtocolError> {
        let descriptors = self.file_containing_symbol(service_name).await?;

        for desc_bytes in &descriptors {
            let file_desc = FileDescriptorProto::decode(desc_bytes.as_slice()).map_err(|e| {
                ProtocolError::Protocol(format!("Parse FileDescriptorProto: {}", e))
            })?;

            for service in file_desc.service.iter() {
                let svc_name = service.name.clone().unwrap_or_default();
                let svc_full = match &file_desc.package {
                    Some(pkg) => format!("{}.{}", pkg, svc_name),
                    None => svc_name.clone(),
                };

                if svc_full == service_name {
                    for method in service.method.iter() {
                        if method.name.as_deref() == Some(method_name) {
                            return Ok(MethodDescriptorInfo {
                                input_type: method.input_type.clone().unwrap_or_default(),
                                output_type: method.output_type.clone().unwrap_or_default(),
                                client_streaming: method.client_streaming.unwrap_or(false),
                                server_streaming: method.server_streaming.unwrap_or(false),
                            });
                        }
                    }
                }
            }
        }

        Err(ProtocolError::Protocol(format!(
            "Method {}/{} not found via reflection",
            service_name, method_name
        )))
    }

    /// Build the complete service descriptor cache
    pub async fn build_cache(&mut self) -> Result<ServiceDescriptorCache, ProtocolError> {
        let services = self.list_services().await?;
        let mut cache = ServiceDescriptorCache {
            services: services.clone(),
            ..Default::default()
        };

        // Fetch descriptors for all services in parallel: each client holds its own Channel clone, so they can run concurrently.
        // Avoids N serial RTTs when there are many services (e.g. 20 services = 20 round trips).
        let fetches: Vec<_> = services
            .iter()
            .map(|service_name| {
                let mut client = self.clone();
                let service_name = service_name.clone();
                async move {
                    (
                        service_name.clone(),
                        client.file_containing_symbol(&service_name).await,
                    )
                }
            })
            .collect();
        let results = futures_util::future::join_all(fetches).await;

        for (service_name, result) in results {
            match result {
                Ok(descriptors) => {
                    for desc_bytes in &descriptors {
                        let file_desc = FileDescriptorProto::decode(desc_bytes.as_slice())
                            .map_err(|e| {
                                ProtocolError::Protocol(format!("Parse FileDescriptorProto: {}", e))
                            })?;

                        for service in file_desc.service.iter() {
                            let svc_name = service.name.clone().unwrap_or_default();
                            let svc_full_name = match &file_desc.package {
                                Some(pkg) => format!("{}.{}", pkg, svc_name),
                                None => svc_name,
                            };

                            if svc_full_name == *service_name {
                                for method in service.method.iter() {
                                    let method_key = format!(
                                        "{}/{}",
                                        svc_full_name,
                                        method.name.clone().unwrap_or_default()
                                    );
                                    cache.methods.insert(
                                        method_key,
                                        MethodDescriptorInfo {
                                            input_type: method
                                                .input_type
                                                .clone()
                                                .unwrap_or_default(),
                                            output_type: method
                                                .output_type
                                                .clone()
                                                .unwrap_or_default(),
                                            client_streaming: method
                                                .client_streaming
                                                .unwrap_or(false),
                                            server_streaming: method
                                                .server_streaming
                                                .unwrap_or(false),
                                        },
                                    );
                                }
                            }
                        }
                    }
                    cache.file_descriptors.insert(service_name, descriptors);
                }
                Err(e) => {
                    tracing::warn!("Failed to get descriptor for {}: {}", service_name, e);
                }
            }
        }

        Ok(cache)
    }

    /// Send a reflection request and receive the response
    async fn send_reflection_request(
        &mut self,
        request: ServerReflectionRequest,
    ) -> Result<ServerReflectionResponse, ProtocolError> {
        let request_bytes = prost::Message::encode_to_vec(&request);
        let framed_request = encode_grpc_frame(request_bytes);

        let uri: http::Uri =
            "http://localhost/grpc.reflection.v1alpha.ServerReflection/ServerReflectionInfo"
                .parse()
                .map_err(|e| ProtocolError::Protocol(format!("Invalid URI: {}", e)))?;

        let http_req = hyper::Request::builder()
            .method(hyper::Method::POST)
            .uri(uri)
            .header("content-type", "application/grpc+proto")
            .header("te", "trailers")
            // gRPC messages must carry a 5-byte frame header
            .body(http_body_util::Full::new(framed_request))
            .map_err(|e| ProtocolError::Send(e.to_string()))?;

        let (parts, body) = http_req.into_parts();
        let tonic_req = http::Request::from_parts(parts, tonic::body::Body::new(body));

        let mut channel = self.channel.clone();
        channel
            .ready()
            .await
            .map_err(|e| ProtocolError::Connect(format!("Reflection channel not ready: {e}")))?;

        let resp = channel
            .call(tonic_req)
            .await
            .map_err(|e| ProtocolError::Send(format!("Reflection call failed: {}", e)))?;

        let body_bytes = http_body_util::BodyExt::collect(resp.into_body())
            .await
            .map_err(|e| ProtocolError::Receive(e.to_string()))?
            .to_bytes();

        // Decode the gRPC frame (skip the 5-byte frame header)
        let payload = if body_bytes.len() > 5 {
            &body_bytes[5..]
        } else {
            &body_bytes[..]
        };

        let response = <ServerReflectionResponse as ProstMessage>::decode(payload)
            .map_err(|e| ProtocolError::Protocol(format!("Decode reflection response: {}", e)))?;

        Ok(response)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_method_descriptor_info() {
        let info = MethodDescriptorInfo {
            input_type: ".test.Request".into(),
            output_type: ".test.Response".into(),
            client_streaming: false,
            server_streaming: true,
        };
        assert_eq!(info.input_type, ".test.Request");
        assert!(info.server_streaming);
        assert!(!info.client_streaming);
    }

    #[test]
    fn test_service_descriptor_cache_default() {
        let cache = ServiceDescriptorCache::default();
        assert!(cache.services.is_empty());
        assert!(cache.methods.is_empty());
    }

    #[test]
    fn test_reflection_request_encoding() {
        let request = ServerReflectionRequest {
            host: String::new(),
            message_request: Some(server_reflection_request::MessageRequest::ListServices(
                String::new(),
            )),
        };

        let bytes = prost::Message::encode_to_vec(&request);
        assert!(!bytes.is_empty());

        let decoded = ServerReflectionRequest::decode(bytes.as_slice()).unwrap();
        assert!(matches!(
            decoded.message_request,
            Some(server_reflection_request::MessageRequest::ListServices(_))
        ));
    }

    #[test]
    fn test_reflection_request_file_containing_symbol() {
        let request = ServerReflectionRequest {
            host: String::new(),
            message_request: Some(
                server_reflection_request::MessageRequest::FileContainingSymbol(
                    "test.Service".into(),
                ),
            ),
        };

        let bytes = prost::Message::encode_to_vec(&request);
        let decoded = ServerReflectionRequest::decode(bytes.as_slice()).unwrap();

        match decoded.message_request {
            Some(server_reflection_request::MessageRequest::FileContainingSymbol(s)) => {
                assert_eq!(s, "test.Service");
            }
            _ => panic!("Wrong message_request variant"),
        }
    }
}
